name: cycif-normalization-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - pandas
  - dask
  - zarr
  - scikit-image
  - tifffile
  - scikit-learn
  - scipy
  - pip:
      - pyometiff
      - scikit-fda