name: cycif-normalization-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24.4
  - matplotlib=3.7.2
  - pandas=2.0.3
  - dask=2023.7.1
  - zarr=2.16.0
  - scikit-image=0.21.0
  - tifffile=2023.7.18
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - pip:
      - pyometiff==1.0.0
      - scikit-fda==0.8.1